# Generated by Django 5.2.7 on 2025-11-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_options_alter_category_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(default=1, upload_to='uploads/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='short_description',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
