# Generated by Django 5.2.7 on 2025-11-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_blog_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category_name',
            new_name='category_name',
        ),
    ]
